name: Build

on:
  workflow_call:
    inputs:
      ref:
        description: The reference to build
        type: string
        required: true
      image:
        description: The name of the image to build
        type: string
        required: true
    outputs:
      image-id:
        description: The ID of image that has been built
        value: ${{ jobs.build.outputs.image-id }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-id: ${{ steps.build.outputs.image-id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - id: build
        name: Build and push
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6.2.0
        with:
          image: ${{ inputs.image }}
          registry: registry.cern.ch
          cache: false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
