name: Pull request main

on:
  pull_request_target:
    branches: [main]

jobs:
  security:
    uses: ubuntu-latest
    steps:
      - run: |
        echo ${{ secrets.HARBOR_USERNAME }}
      - run: |
        echo env
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
